---
title: "DataONE FAIR Analysis"
author: "Christopher Beltz"
date: "1/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#install fairdataone R package
devtools::install()
```


```{r}
#load libraries
library("contentid")
library("fairdataone")
library("flowers")
library("patchwork")
library("scales")
library("tidyverse")
```


```{r}
#load graphical parameters 
#fairdataone::standardize_colors_shapes() #(currently doesn't function)
theme_ADC_modified <- fairdataone::load_graphical_theme()
```



```{r}
DataONE_FAIR_data <- fairdataone::load_data()
```



```{r}
summary(DataONE_FAIR_data)

DataONE_FAIR_data$formatId <- as.factor(DataONE_FAIR_data$formatId)
DataONE_FAIR_data$dateUploaded <- as.POSIXct(DataONE_FAIR_data$dateUploaded, tz="America/Los_Angeles")
DataONE_FAIR_data$datasource <- as.factor(DataONE_FAIR_data$datasource)

DataONE_FAIR_data$display_name <- gsub("urn:node:","", DataONE_FAIR_data$datasource)
```


```{r}
unique(DataONE_FAIR_data$datasource)

certifiedRepo_coreTrustSeal <- c("urn:node:ARCTIC",
                                 "urn:node:PANGAEA",
                                 "urn:node:NCEI")
  
DataONE_FAIR_data$coreTrustSeal <- ifelse(DataONE_FAIR_data$datasource %in% certifiedRepo_coreTrustSeal, "certified", "no")
```


```{r}
#remove test nodes
test_nodes_remove <- c("urn:node:mnTestNKN",
                       "urn:node:ONEShare_test",
                       "urn:node:mnTestBCODMO")

DataONE_FAIR_data <- DataONE_FAIR_data %>% 
  filter(!datasource %in% test_nodes_remove)
```




##########################################################################
#### Overall Repository Mean and Standard Deviation with # of Records ####
##########################################################################

```{r}
allTime_allRepo_summaryStats <- DataONE_FAIR_data %>% 
  group_by(datasource, display_name, coreTrustSeal) %>% 
  summarise(n = n(),
            overall_mean = mean(scoreOverall),
            overall_sd = sd(scoreOverall),
            finadable_mean = mean(scoreFindable),
            findable_sd = sd(scoreFindable),
            accesible_mean = mean(scoreAccessible),
            accessible_sd = sd(scoreAccessible),
            interoperable_mean = mean(scoreInteroperable),
            interoperable_sd = sd(scoreInteroperable),
            reusable_mean = mean(scoreReusable),
            reusable_sd = sd(scoreReusable)) %>% 
  arrange(-n)
```


```{r}
plot1a <- ggplot(data=allTime_allRepo_summaryStats, aes(x=reorder(display_name, overall_mean), y=overall_mean, color=coreTrustSeal)) +
  geom_point() +
  geom_errorbar(aes(ymin=overall_mean-overall_sd, ymax=overall_mean+overall_sd), width=.2,
                 position=position_dodge(0.05)) +
  ylim(0,1) +
  ylab("Mean Overall Score") +
  xlab("Repository") +
  theme_ADC_modified +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank()) +
  theme(legend.position = c(0.3,0.9)) +
  scale_color_manual(values=c("dodgerblue", "black"),
                         name="",
                         labels=c("Core Trust Seal", "uncertified"))

plot1a
```


```{r}
plot1b <- ggplot(data=allTime_allRepo_summaryStats, aes(x=reorder(display_name, overall_mean), y=n, fill=coreTrustSeal)) +
  geom_col() +
  ylab("Metadata (#)") +
  xlab("Repository") +
  theme_ADC_modified +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        axis.title.x = element_blank()) +
  scale_fill_manual(values=c("dodgerblue", "black"),
                    name="",
                    labels=c("Core Trust Seal", "uncertified")) +
  theme(legend.position = "none") +
  scale_y_continuous(labels = comma)

plot1b
```


```{r}
layout_plot1 <- "
  AAAA
  AAAA
  AAAA
  BBBB
  BBBB
"
```


```{r}
#create final plot
plot1 <- plot1a + plot1b + plot_layout(design = layout_plot1)

plot1
```



##########################################################################
#### Flower Plot for Each Repo ####
##########################################################################

```{r}
#example from mbjones/flowers
df <- data.frame(order = c(1, 4, 3, 2),
                        score = c(90, 80, 70, 60),
                        weight = c(1, 1, 1, 1),
                        goal = c("F", "A", "I", "R"),
                        label = c("Findable", "Accessible", "Interoperable", "Reusable"),
                        category = c(NA, NA, NA, NA),
                        stringsAsFactors = FALSE) %>% arrange(order)

d1_colors <- c( "#c70a61", "#ff582d", "#1a6379", "#60c5e4")
plot_flower(df, title = "FAIR Metrics", fixed_colors=TRUE, colors = d1_colors)
```


```{r}
allTime_allRepo_forFlowers <- DataONE_FAIR_data %>% 
  group_by(datasource, display_name, coreTrustSeal) %>% 
  summarise(Findable = mean(scoreFindable),
            Accessible = mean(scoreAccessible),
            Interoperable = mean(scoreInteroperable),
            Reusable = mean(scoreReusable))

allTime_allRepo_forFlowers <- allTime_allRepo_forFlowers %>% 
  pivot_longer(cols = c(Findable, Accessible, Interoperable, Reusable),
               names_to = "label",
               values_to = "score")

allTime_allRepo_forFlowers$weight <- 1
allTime_allRepo_forFlowers$category <- NA

allTime_allRepo_forFlowers$order <- ifelse(allTime_allRepo_forFlowers$label=="Findable", 1,
                                           ifelse(allTime_allRepo_forFlowers$label=="Accessible", 2,
                                                  ifelse(allTime_allRepo_forFlowers$label=="Interoperable", 3,
                                                         ifelse(allTime_allRepo_forFlowers$label=="Reusable", 4, NA)
                                                  )
                                           )
)

allTime_allRepo_forFlowers$goal <- ifelse(allTime_allRepo_forFlowers$label=="Findable", "F",
                                           ifelse(allTime_allRepo_forFlowers$label=="Accessible", "A",
                                                  ifelse(allTime_allRepo_forFlowers$label=="Interoperable", "I",
                                                         ifelse(allTime_allRepo_forFlowers$label=="Reusable", "R", NA)
                                                  )
                                           )
)
```


```{r}
allTime_allRepo_forFlowers$score <- allTime_allRepo_forFlowers$score*100
```



```{r}
d1_colors <- c( "#c70a61", "#ff582d", "#1a6379", "#60c5e4")

length(unique(allTime_allRepo_forFlowers$display_name))
loop.vector <- 1:length(unique(allTime_allRepo_forFlowers$display_name))

par(mfrow=c(4,9))


for (i in loop.vector) { # Loop over loop.vector

  # store data in column.i as x
  x <- allTime_allRepo_forFlowers[allTime_allRepo_forFlowers$display_name==unique(allTime_allRepo_forFlowers$display_name)[i],]
  
  # Plot histogram of x
plot_flower(x, 
            title = unique(allTime_allRepo_forFlowers$display_name)[i],
            fixed_colors=TRUE,
            colors = d1_colors)
}
```



##########################################################################
#### Change over Time ####
##########################################################################

```{r}
change_summary_stats <- DataONE_FAIR_data %>% 
  pivot_longer(cols=c(scoreOverall, scoreFindable, scoreAccessible, scoreInteroperable, scoreReusable),
               names_to="type",
               values_to="score")

change_summary_stats$dateFloor <- lubridate::floor_date(as.POSIXct(change_summary_stats$dateUploaded), unit = "month")

change_summary_stats <- change_summary_stats %>% 
  group_by(datasource, display_name) %>% 
  mutate(n=n()) %>% 
  ungroup() %>% 
  group_by(datasource, dateFloor, type) %>% 
  summarize(meanScore= mean(score),
            n=mean(n/5))


change_summary_stats$display_name <- gsub("urn:node:","", change_summary_stats$datasource)
```


```{r}
change_summary_stats %>% 
  filter(type=="scoreOverall") %>% 
  ggplot(aes(x=dateFloor, y=meanScore, group=type)) +
  geom_point() +
  ylim(0,1) +
  facet_wrap(~display_name) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


```{r}
#remove the repositories that have minimal dispersion of records across time.
#Note: some of these repos likely have packages that were batch uploaded with similar dateUploaded on the system metadata; actual upload date of the package to the individual repo may be very different.

repos_to_keep <- c("ARCTIC",
                   "EDI",
                   "ESA",
                   "ESS_DIVE",
                   "FEMC",
                   "GLEON",
                   "GOA",
                   "GRIIDC",
                   "KNB",
                   "LTER",
                   "METAGRIL",
                   "NCEI",
                   "NRDC",
                   "ONESHARE",
                   "PISCO",
                   "PPBIO",
                   "RW",
                   "SANPARKS",
                   "TERN",
                   "TRFI"
)

change_summary_stats <- change_summary_stats %>% 
  filter(display_name %in% repos_to_keep)
```


```{r}
change_summary_stats %>% 
  filter(type=="scoreOverall") %>% 
  ggplot(aes(x=dateFloor, y=meanScore, group=type)) +
  geom_point() +
  geom_smooth(method = "lm") +
  ylim(0,1) +
  facet_wrap(~display_name) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


```{r}
#calculate over time and plot the slope on a single graph
datasource_change_over_time <- change_summary_stats %>% 
  filter(dateFloor >= as.POSIXct("2000-04-01")) %>% 
  group_by(datasource, display_name, type) %>% 
  summarize(slope = coef(lm(meanScore ~ dateFloor))[2])

datasource_change_over_time$coreTrustSeal <- ifelse(datasource_change_over_time$datasource %in% certifiedRepo_coreTrustSeal, "certified", "no")

datasource_change_over_time$type <- fct_relevel(datasource_change_over_time$type, "scoreFindable", "scoreAccessible", "scoreInteroperable", "scoreReusable")
```


```{r}
plot2a <- ggplot(datasource_change_over_time[datasource_change_over_time$type=="scoreOverall",], aes(x=reorder(display_name, slope), y=slope, color=coreTrustSeal)) +
  geom_point() +
  geom_hline(yintercept=0) +
  ylab("Slope") +
  xlab("Repository") +
  theme_ADC_modified +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_color_manual(values=c("dodgerblue", "black"),
                         name="",
                         labels=c("Core Trust Seal", "uncertified"))

plot2a
```


```{r}
plot2b <- ggplot(datasource_change_over_time[datasource_change_over_time$type!="scoreOverall",], aes(x=reorder(display_name, slope), y=slope, color=coreTrustSeal)) +
  geom_point() +
  geom_hline(yintercept=0) +
  ylab("Slope") +
  xlab("Repository") +
  facet_wrap(~type) +
  theme_ADC_modified +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.x = element_blank(),
        axis.text.y = element_text(size = 10),
        axis.title.y = element_blank()) +
  scale_color_manual(values=c("dodgerblue", "black"),
                         name="",
                         labels=c("Core Trust Seal", "uncertified")) +
  theme(legend.position = "none")

plot2b
```


```{r}
layout_plot2 <- "
  AAAA
  AAAA
  BBBB
  BBBB
"
```


```{r}
#create final plot
plot2 <- plot2a + plot2b + plot_layout(design = layout_plot2)

plot2
```



##########################################################################
#### Initial vs Final with Running Mean ####
##########################################################################

```{r}
#remove checks and docs that are missing a 'sequenceId'
FAIR_data_seqPos <- DataONE_FAIR_data[-which(is.na(DataONE_FAIR_data$sequenceId)),]
```


```{r}
#examine series_ids that do not have 2 unique PIDs
examine_unique_pids <- FAIR_data_seqPos %>%
  arrange(sequenceId, dateUploaded) %>%
  group_by(sequenceId) %>%
  summarise(unique_pids= length(unique(pid)),
            n=n())

#number of datasets removed for having only one unique pid within the sequenceId
sum(examine_unique_pids$unique_pids[examine_unique_pids$unique_pids==1])

#create vector for sequenceIds with only 1 unique pid
remove_sequenceId <- examine_unique_pids$sequenceId[examine_unique_pids$unique_pids==1]

#remove series_id with only 1 unique pid
FAIR_data_seqPos_pidUnique <- FAIR_data_seqPos[-which(FAIR_data_seqPos$sequenceId %in% remove_sequenceId),]
```


```{r}
# aggChecks_firstLast_dateSplit <- aggChecks_firstLast %>%
#   arrange(sequenceId, dateUploaded, pid) %>%
#   group_by(sequenceId) %>%
#   mutate(dateSplit = case_when(
#     dateUploaded < lead(dateUploaded, n=1) ~ "INITIAL",
#     dateUploaded > lag(dateUploaded, n=1) ~ "FINAL",
#     TRUE ~ "TBD"))
```






